"use client"

import { useState } from "react"
import {
  InstrumentHead,
  InstrumentNote,
  When,
  useInstrument,
} from "@/components/kit/InstrumentStatus"
import { absDateTime, ageWords } from "@/lib/instrument-status"
import { useSenses } from "./senses"

// The box's newest camera frame. /eyes.png is regenerated by the snapshot timer
// once a minute, and it keeps being served after the timer stops: the route
// answers 200 for as long as the file exists.
//
// This used to reload the image every minute with a Date.now() cache-buster and
// caption it with the time of the RELOAD, under a blue "LIVE" badge. With the
// cameras unplugged that was a three-week-old frame captioned "last 10:42:07".
// The image is now keyed on the frame's own capture time (so an unchanged frame
// is not re-downloaded at all, and it is 1.2 MB), the caption gives that time,
// and the badge appears only while the frame is actually fresh.
export function LiveEye() {
  const { senses, meta, asked, error } = useSenses(30_000)
  // The src that failed to load, not a bare flag: a flag would stay set when a
  // new frame arrives, and with no <img> mounted nothing would ever clear it.
  const [deadSrc, setDeadSrc] = useState<string | null>(null)

  // latest.json's epoch is the capture time the camera script recorded; the
  // JPEG's mtime is the fallback if the sidecar is missing.
  const captured = meta?.epoch ?? senses?.camera ?? null
  const inst = useInstrument("camera", { lastHeard: captured, error, pending: !asked })
  const live = inst.reading?.state === "live"
  const capturedMs = inst.lastHeardMs
  const src = capturedMs != null ? `/eyes.png?t=${capturedMs}` : null
  const dead = src !== null && deadSrc === src

  return (
    <InstrumentHead name="Eye" status={inst}>
      {inst.reading && !live && (
        <InstrumentNote>
          {capturedMs == null ? (
            <>
              <b>The camera has no frame to give.</b> The snapshot file is missing or unreadable.
            </>
          ) : inst.reading.state === "stale" ? (
            <>
              <b>The newest frame is late.</b> The camera normally delivers one a minute, and this
              one was captured <When at={capturedMs} now={inst.now} />.
            </>
          ) : (
            <>
              <b>The camera is not delivering frames.</b> This is the last one it took, captured{" "}
              <When at={capturedMs} now={inst.now} />, not what is in front of the machine now.
            </>
          )}{" "}
          This board checks every 30 seconds and resumes by itself when frames do.
        </InstrumentNote>
      )}

      <figure className="beta-eye">
        <div className="beta-eye__frame">
          {!src || dead ? (
            <div className="beta-eye__dead">
              {!asked ? "asking for the newest frame" : "camera frame unavailable"}
            </div>
          ) : (
            // eslint: project config doesn't enable @next/next/no-img-element; a
            // frame keyed on its capture time is exactly what <img> is for here.
            <img
              src={src}
              alt={
                live
                  ? "the latest frame from the machine's camera"
                  : capturedMs != null
                    ? `a frame from the machine's camera, captured ${absDateTime(capturedMs)}`
                    : "a frame from the machine's camera"
              }
              onError={() => setDeadSrc(src)}
            />
          )}
          {/* Blue is ACTIVE: shown only while the frame is fresh. */}
          {live && !dead && (
            <span className="beta-eye__live" aria-hidden>
              <span className="beta-eye__dot" /> LIVE
            </span>
          )}
        </div>
        <figcaption className="beta-inst-cap">
          {capturedMs == null
            ? "what the machine sees, when the camera is attached"
            : live && inst.reading?.ageS != null
              ? `what the machine sees · captured ${ageWords(inst.reading.ageS)} ago · a new frame every minute`
              : `the last frame the camera delivered · captured ${absDateTime(capturedMs)}`}
        </figcaption>
      </figure>
    </InstrumentHead>
  )
}
