"use client"

import { useEffect, useState } from "react"

// The box's actual camera frame, refreshed every minute. /eyes.png is served
// no-store and regenerated by the snapshot timer, so a cache-busted reload
// shows whatever the machine is looking at right now.
export function LiveEye() {
  const [src, setSrc] = useState("/eyes.png")
  const [stamp, setStamp] = useState("")
  const [dead, setDead] = useState(false)

  useEffect(() => {
    const tick = () => {
      setSrc(`/eyes.png?t=${Date.now()}`)
      setStamp(new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit", second: "2-digit" }))
    }
    tick()
    const id = setInterval(tick, 60000)
    return () => clearInterval(id)
  }, [])

  return (
    <figure className="v3-meatball-eye">
      <div className="v3-meatball-eye__frame">
        {dead ? (
          <div className="v3-meatball-eye__dead">camera frame unavailable</div>
        ) : (
          // eslint: project config doesn't enable @next/next/no-img-element; a
          // live, cache-busted endpoint is exactly what <img> is for here.
          <img
            src={src}
            alt="the latest frame from the machine's camera"
            onError={() => setDead(true)}
            onLoad={() => setDead(false)}
          />
        )}
        <span className="v3-meatball-eye__live" aria-hidden>
          <span className="v3-meatball-eye__dot" /> LIVE
        </span>
      </div>
      <figcaption>
        what the machine sees · refreshes every minute{stamp ? ` · last ${stamp}` : ""}
      </figcaption>
    </figure>
  )
}
