import Link from "next/link"
import { coverageText, daysInclusive, loadPilotData, longDate, tokens } from "../_pilot-data"
import { BarStrip, CalendarHeat, RampKey, type ChartTick } from "../_charts"
import { BetaMeasured } from "../_measured"
import { costNum, costWindow, loadCostModel } from "../_cost-model"
import { ShiftFigure, ShiftKind } from "@/components/shift/ShiftFigure"
import { CompoundCycle } from "@/components/shift/CompoundCycle"
import { ShiftRows } from "@/components/shift/ShiftRows"

export const revalidate = 3600

// Metadata lives in ./layout.tsx, with the structured data, so the title and
// the share card are written in one place.

/** A share of a whole as text: "98.4%", and "0.01%" where one decimal would print zero. */
function share(part: number, whole: number): string {
  if (!(whole > 0)) return "0%"
  const p = (part / whole) * 100
  return `${p >= 0.1 ? p.toFixed(1) : p.toFixed(2)}%`
}

/**
 * The shift.
 *
 * The previous site argued this over 1,075 lines, with a radar, two donuts,
 * count-up numbers and a diagram. The port cut it to five headings with a
 * number under each, which kept the evidence and dropped the argument: a
 * reader could see 98.4% and not be told what it was a reason for.
 *
 * This version puts the argument back as prose a reader can follow, in the
 * owner's own words where they still hold, with the figures that carry real
 * information and none of the ones that did not:
 *   - the radar is a row chart on its real 0 to 100 scale (one hue; a
 *     radar's area means nothing);
 *   - the two time donuts are one modelled chart and one recorded chart, side
 *     by side and labelled as such, because the "AI-assisted" donut (85%
 *     productive output) was never measured by anything;
 *   - the sprint-against-stream bars (25% and 95%) were drawn, not counted,
 *     and are replaced by the calendar of days a session ran (the pilot
 *     record). The frozen case study's weekly commit counts are every
 *     author's in the organisation, so they stay on /cost-analysis and are
 *     not offered here as evidence of anyone's cadence;
 *   - the compound cycle is back as the kit's numbered sequence.
 *
 * Two sources with two clocks, and the page has to keep them apart:
 * cost-model.json is a FROZEN case study of one fixed window (see
 * app/_cost-model.ts); ai-pilot-data.json is regenerated by its pipeline and
 * carries its own period. Every figure names its file and its period.
 *
 * WHOSE COMMITS. The commit counts in the frozen file are of every author in
 * the organisation's repositories: other contributors and the upstream authors
 * of forked repositories are in them. They are never offered here as evidence
 * about cadence. The calendar is the session record instead, and its note says
 * what a shaded day does and does not mean.
 */
export default function BetaShiftPage() {
  const pilot = loadPilotData()
  const cost = loadCostModel()
  const { frozen, label: windowLabel, recorded } = costWindow(cost)
  const cover = frozen?.coverage

  // Sliced from the ISO string, never parsed into a Date: the stamp carries no
  // zone, and a parsed one can land on the wrong side of midnight.
  const pilotGenerated = pilot.generated ? pilot.generated.slice(0, 10) : null
  const pilotSince = longDate(pilot.coverage?.since)
  const pilotThrough = longDate(pilot.coverage?.through)
  const pilotPeriod =
    pilotSince && pilotThrough ? `${pilotSince} to ${pilotThrough}` : "period not recorded"
  const pilotChip = pilotGenerated ? `, generated ${pilotGenerated}` : ", generation date not recorded"

  /* ---- 01: teams to soloists -------------------------------------------- */
  const legacyHeads = cost.legacy.roles.reduce((s, r) => s + r.count, 0)
  const domains = Object.entries(pilot.instrumentRatings)
    .sort((a, b) => b[1].score - a[1].score)
    .map(([name, r]) => ({ label: name, value: r.score, display: `${r.score}` }))
  const sampled = pilot.coverage?.rollingWindow?.filesSampled

  /* ---- 02: sprints to streams ------------------------------------------- */
  // The session calendar. A day counts when any Claude Code session on the
  // record wrote to it (UTC days). It is the record of when sessions ran, which
  // is what the cadence argument needs; the frozen file's commit counts are
  // every author's and stay on /cost-analysis.
  const sessionDays = pilot.activityHeatmap.map((a) => ({ date: a.date, value: a.count }))
  const since = pilot.coverage?.since ?? pilot.activityHeatmap[0]?.date
  const through = pilot.coverage?.through ?? pilot.activityHeatmap.at(-1)?.date
  const periodDays = daysInclusive(since, through)
  const activeDays = pilot.activityHeatmap.filter((a) => a.count > 0).length
  const blankDays = periodDays !== null ? periodDays - activeDays : null
  const S = pilot.streaks
  // "Every day since X" is only said when the current run is the longest one
  // and it ends on the record's last day, so the start date is the run's own.
  const runStart =
    S.current > 1 && S.current === S.longest && S.longestStart && S.longestEnd === through
      ? S.longestStart
      : null
  // Every blank day is before the run. If the run began before the record was
  // kept as it happened, those blanks sit in the reconstructed part of it.
  const began = pilot.coverage?.recordingBegan
  const blanksAreReconstructed = Boolean(runStart && began && runStart < began)
  const dayZone = pilot.coverage?.dayTimezone ?? S.timezone ?? "UTC"
  const calendarOk = Boolean(since && through && periodDays !== null && activeDays > 0)

  /* ---- 03: meetings to messages ----------------------------------------- */
  // The model's assumption about a developer's week on a conventional team.
  // Three shares are written into the model; the rest is not itemised there,
  // and the page says so instead of inventing a breakdown.
  const bench = cost.industryBenchmarks
  const benchKnown =
    typeof bench.codingTimePercent === "number" &&
    typeof bench.meetingTimePercent === "number" &&
    typeof bench.codeReviewPercent === "number"
      ? {
          coding: bench.codingTimePercent,
          meetings: bench.meetingTimePercent,
          review: bench.codeReviewPercent,
        }
      : null
  const benchRest = benchKnown ? 100 - benchKnown.coding - benchKnown.meetings - benchKnown.review : 0
  const benchRows = benchKnown
    ? [
        { label: "Coding", value: benchKnown.coding, display: `${benchKnown.coding}%` },
        { label: "Meetings", value: benchKnown.meetings, display: `${benchKnown.meetings}%` },
        { label: "Review", value: benchKnown.review, display: `${benchKnown.review}%` },
        // The remainder is not a fourth assumption: it is what the model leaves
        // unsaid, so it is drawn as an outline and listed last.
        { label: "Not itemised", value: benchRest, display: `${benchRest}%`, open: true },
      ]
    : []

  // When the recorded work happened. `records` is every transcript record
  // stamped in that hour over the whole durable record; a file written before
  // the pipeline carried it has only a session count, and then there is no
  // figure rather than a different one under the same caption.
  const hours = pilot.hourlyDistribution.hours.map((h) => ({
    hour: h.hour,
    label: h.label,
    records: h.records,
  }))
  const hoursOk = hours.length === 24 && hours.every((h) => typeof h.records === "number")
  const hourTotal = hoursOk ? hours.reduce((s, h) => s + (h.records ?? 0), 0) : 0
  const officeHours = hoursOk
    ? hours.filter((h) => h.hour >= 9 && h.hour < 17).reduce((s, h) => s + (h.records ?? 0), 0)
    : 0
  const peakHour = hoursOk
    ? hours.reduce((m, h) => ((h.records ?? 0) > (m.records ?? 0) ? h : m), hours[0])
    : null
  const hourZone = pilot.hourlyDistribution.timezone ?? "UTC"
  const hourTicks: ChartTick[] = [0, 6, 12, 18].map((h) => ({ at: h, label: `${String(h).padStart(2, "0")}:00` }))

  /* ---- 04: the cache effect --------------------------------------------- */
  const tok = pilot.tokenEconomy
  const inputAll = tok.totalCacheReadTokens + tok.totalCacheCreateTokens + tok.totalInputTokens
  // The value printed on each row is its share of all input. The token counts
  // go in the note under the chart: on a phone a row has room for one number
  // beside its bar.
  const inputRows = [
    { label: "From cache", value: tok.totalCacheReadTokens },
    { label: "To cache", value: tok.totalCacheCreateTokens },
    { label: "Fresh", value: tok.totalInputTokens },
  ].map((r) => ({
    label: r.label,
    value: inputAll > 0 ? (r.value / inputAll) * 100 : 0,
    display: share(r.value, inputAll),
  }))
  // How many times smaller the fresh share is than the one above it. The
  // fresh bar is below one pixel at any width, and the note has to say so.
  const freshTimes =
    tok.totalInputTokens > 0 ? Math.round(tok.totalCacheCreateTokens / tok.totalInputTokens) : null

  /* ---- 05: compound velocity -------------------------------------------- */
  const projectCount = pilot.license.projectCount.toLocaleString("en-US")
  const corrections = (frozen as { corrections?: unknown[] } | undefined)?.corrections?.length

  return (
    <div className="page">
      <div className="page-head">
        <nav className="crumb" aria-label="Breadcrumb">
          <Link href="/">bradley.io</Link>
          <span>
            {" / "}
            <span aria-current="page">The shift</span>
          </span>
        </nav>
        <h1>The shift</h1>
      </div>

      <p className="lede">
        How AI rewrites the economics of building software. Five sections of evidence, not vibes,
        and a note wherever the evidence runs out.
      </p>

      <div className="notice">
        <b>One project, one operator.</b> Everything below is drawn from a single body of work. It
        is a description of what happened here, not a claim about what happens generally.
      </div>

      {/* Two sources with two clocks. The team model is the frozen cost case
          study; every chart of activity is the pilot record. Saying "one
          window" for both was untrue. */}
      <div className="notice">
        <b>{frozen ? "Part of this page is frozen." : "Two sources."}</b> The modelled team, its
        seats and its working week, comes from a case study of one fixed window, {windowLabel},
        recorded on {recorded}
        {frozen ? ". It is not a live figure and does not update" : ""}. The coverage chart, the
        calendar, the hours and the token figures come from the pilot record
        {pilotGenerated ? `, last generated ${pilotGenerated}` : ""}, and cover its own period.
        Each figure names its file and its period underneath.
      </div>

      <div className="prose beta-sec beta-shift-thesis">
        <p>
          The argument runs in five steps. Teams collapse into soloists. Sprints stretch into
          streams. Meetings are replaced by messages. The cache makes a long context affordable.
          And the work compounds, because every project leaves tools behind for the next one. Each
          section makes one of those claims, shows the figure behind it, and says what that figure
          cannot carry.
        </p>

        {/* ============================================================
            01
            ============================================================ */}
        <h2>
          <span className="beta-shift-n">01</span>From teams to soloists
        </h2>
        <p>
          {legacyHeads} roles worth of surface area, covered by {cost.actual.teamSize}.
        </p>
        <p>
          AI doesn&rsquo;t just make you faster at what you already know. It makes adjacent domains
          accessible: security, DevOps, systems programming. Domains that used to need a dedicated
          hire become reachable with the right co-pilot.
        </p>
        <p>
          The ratings below are keyword coverage over project notes, plan files and the
          technologies named in about the last 30 days of session logs, so they show breadth of
          work touched rather than depth of expertise. A high score says the month was spent in that
          vocabulary. It does not certify a specialist.
        </p>
      </div>

      <RampKey low="lower" high="higher" />

      <ShiftFigure
        kind="recorded"
        labels="mid"
        source="ai-pilot-data.json"
        note={`, instrumentRatings${typeof sampled === "number" ? `, ${sampled} session logs sampled` : ""}, about the last 30 days${pilotChip}`}
      >
        <div className="panel">
          <div className="panel-face">
            <div className="panel-bar">
              <b>Domain coverage, 0 to 100</b>
              <ShiftKind kind="recorded" />
            </div>
            <ShiftRows
              caption="Keyword coverage by engineering domain, about the last 30 days of session logs"
              data={domains}
              max={100}
              axis={["0", "50", "100"]}
            />
          </div>
        </div>
      </ShiftFigure>

      <div className="prose beta-sec">
        <p>The seats the cost model prices for the same ground:</p>
      </div>
      <ul className="beta-shift-seats" aria-label="Roles in the modelled team">
        {cost.legacy.roles.map((r) => (
          <li className="tag" key={r.title}>
            {r.title}
            {r.count > 1 ? ` x${r.count}` : ""}
            {r.halfTime ? ", half time" : ""}
          </li>
        ))}
      </ul>

      {/* ==============================================================
          02
          ============================================================== */}
      <div className="prose beta-sec">
        <h2>
          <span className="beta-shift-n">02</span>From sprints to streams
        </h2>
        <p>
          The sprint model assumes work arrives in discrete batches. AI-assisted development is
          continuous: deploy when ready, iterate in real time, no ceremony between idea and
          production.
        </p>
        {calendarOk && (
          <p>
            The pilot record draws that as a calendar. Sessions ran on {activeDays} of the{" "}
            {periodDays} days it covers
            {runStart ? `, and on every day since ${longDate(runStart)}` : ""}.
            {blankDays && blanksAreReconstructed && began
              ? ` All ${blankDays} blank days fall before ${longDate(began)}, when the record began to be kept as it happened. Before then it holds only the logs still on disk that day, so a blank there can be a pruned log as easily as a day off.`
              : ""}
          </p>
        )}
      </div>

      {calendarOk && since && through && (
        <ShiftFigure
          kind="recorded"
          source="ai-pilot-data.json"
          note={`, activityHeatmap, ${pilotPeriod}, ${dayZone} days${pilotChip}`}
        >
          <div className="panel">
            <div className="panel-face">
              <div className="panel-bar">
                <b>Days a session ran</b>
                <ShiftKind kind="recorded" />
              </div>
              <CalendarHeat
                caption={`Transcript records per ${dayZone} day, ${pilotPeriod}`}
                summary={`Sessions ran on ${activeDays} of ${periodDays} days${
                  runStart ? `, every day since ${longDate(runStart)}` : ""
                }.`}
                days={sessionDays}
                start={since}
                end={through}
                unit="records"
                cellIs={`one ${dayZone} day`}
              />
              <p className="beta-chart__note">
                A day is shaded when any session wrote a record to it, which says sessions were
                running, not that anyone was at a desk.
              </p>
            </div>
          </div>
        </ShiftFigure>
      )}

      <div className="prose beta-sec">
        <p>
          What this cannot show is the counterfactual. Nobody ran the same project in two-week
          sprints to compare. The weekly commit and issue counts for the case-study window are on{" "}
          <Link href="/cost-analysis">cost analysis</Link>; they count every author in the
          organisation&rsquo;s repositories, so they describe the project, not one person&rsquo;s
          cadence.
        </p>

        {/* ============================================================
            03
            ============================================================ */}
        <h2>
          <span className="beta-shift-n">03</span>From meetings to messages
        </h2>
        <p>
          {pilot.license.totalMessages.toLocaleString("en-US")} transcript records across{" "}
          {pilot.license.totalSessions.toLocaleString("en-US")} sessions and{" "}
          {pilot.license.projectCount.toLocaleString("en-US")} projects. The coordination happened
          in the conversation, not on a calendar, and the record can only show the conversation
          half of that.
        </p>
        <p className="quiet">{coverageText(pilot)}</p>
        <p>
          An earlier version of this page set that count beside the words &ldquo;0 meetings.&rdquo;
          The count is real. The zero was a flourish: nothing in the record knows what was on a
          calendar.
          {benchKnown
            ? ` The same goes for the split of a working week. The cost model assumes a developer on a conventional team spends ${benchKnown.coding}% of it writing code, ${benchKnown.meetings}% in meetings and ${benchKnown.review}% in review. There is no such split for the recorded side, because nobody logged one.`
            : ""}{" "}
          What the record does have is when the work happened.
        </p>
      </div>

      <div className="beta-shift-two">
        {benchKnown && (
          <ShiftFigure
            kind="modelled"
            labels="mid"
            source="cost-model.json"
            note=", industryBenchmarks: assumptions written into the model, not measurements"
          >
            <div className="panel">
              <div className="panel-face">
                <div className="panel-bar">
                  <b>A developer&rsquo;s week</b>
                  <ShiftKind kind="modelled" />
                </div>
                <ShiftRows
                  caption="Share of working time on a conventional team, as the cost model assumes it"
                  data={benchRows}
                  max={100}
                  axis={["0%", "50%", "100%"]}
                />
                <p className="beta-chart__note">
                  Three shares are written into the model. The remaining {benchRest}% is not broken
                  down there, so it is not broken down here: its row is an outline, not a
                  measurement.
                </p>
              </div>
            </div>
          </ShiftFigure>
        )}

        {hoursOk && peakHour && (
          <ShiftFigure
            kind="recorded"
            source="ai-pilot-data.json"
            note={`, hourlyDistribution, ${pilotPeriod}, hours in ${hourZone}${pilotChip}`}
          >
            <div className="panel">
              <div className="panel-face">
                <div className="panel-bar">
                  <b>When the work happened</b>
                  <ShiftKind kind="recorded" />
                </div>
                <BarStrip
                  caption={`Transcript records by hour of day, ${hourZone}, ${pilotPeriod}`}
                  summary={`${costNum(hourTotal)} transcript records by hour of day. The busiest hour is ${peakHour.label} with ${costNum(peakHour.records ?? 0)}; ${share(hourTotal - officeHours, hourTotal)} fall outside 09:00 to 17:00.`}
                  data={hours.map((h) => ({ label: h.label, value: h.records ?? 0 }))}
                  unit="records"
                  ticks={hourTicks}
                  height={88}
                />
                <p className="beta-chart__note">
                  {share(hourTotal - officeHours, hourTotal)} of the records fall outside 09:00 to
                  17:00. A record is a prompt, a tool result or one block of a model reply, so this
                  is when sessions were running, not when anyone was typing.
                </p>
              </div>
            </div>
          </ShiftFigure>
        )}
      </div>

      {/* ==============================================================
          04
          ============================================================== */}
      <div className="prose beta-sec">
        <h2>
          <span className="beta-shift-n">04</span>The cache effect
        </h2>
        <p>
          {tok.cacheEfficiency.toFixed(1)}% of input came from cache. That is the whole reason a
          long-running context is affordable: re-reading the project each turn is what the cache is
          paying for.
        </p>
        <p>
          An earlier version of this page called that instant onboarding, and said the model
          retains the context of prior work. It doesn&rsquo;t. The model keeps nothing between
          turns: every turn it is handed the conversation and the files again, and the cache is
          what makes handing them over affordable. It is closer to say that onboarding happens on
          every turn. The conversation is the knowledge base.
        </p>
      </div>

      <ShiftFigure
        kind="recorded"
        source="ai-pilot-data.json"
        note={`, tokenEconomy, ${pilotPeriod}${pilotChip}`}
      >
        <div className="panel">
          <div className="panel-face">
            <div className="panel-bar">
              <b>Input tokens by source</b>
              <ShiftKind kind="recorded" />
            </div>
            <ShiftRows
              caption={`Share of all input tokens, ${pilotPeriod}`}
              data={inputRows}
              max={100}
              axis={["0%", "50%", "100%"]}
            />
            <p className="beta-chart__note">
              {tokens(tok.totalCacheReadTokens)} tokens read from cache,{" "}
              {tokens(tok.totalCacheCreateTokens)} written to it and{" "}
              {tokens(tok.totalInputTokens)} fresh. The rows are drawn to scale: the write to cache
              is a sliver
              {freshTimes !== null && freshTimes > 1
                ? `, and fresh input, about ${freshTimes} times smaller again, is the two-pixel mark`
                : ""}
              . Output over the same period was {tokens(tok.totalOutputTokens)} tokens. Tokens used
              by subagents are not in the record.
            </p>
          </div>
        </div>
      </ShiftFigure>

      {/* ==============================================================
          05
          ============================================================== */}
      <div className="prose beta-sec">
        <h2>
          <span className="beta-shift-n">05</span>Compound velocity
        </h2>
        <p>
          {/* The explicit spaces are load-bearing: a JSX text run that starts with a
              space and holds an entity loses the space in this toolchain. */}
          {projectCount} projects aren&rsquo;t {projectCount}{" "}
          isolated efforts. They&rsquo;re an interconnected ecosystem, and the connection has a
          shape.
        </p>
      </div>

      <CompoundCycle
        steps={[
          {
            title: "Sessions generate code",
            body: `${pilot.license.totalMessages.toLocaleString("en-US")} transcript records of building, in ${pilot.license.totalSessions.toLocaleString("en-US")} sessions.`,
          },
          {
            title: "Code feeds pipelines",
            body: "Some of that code is scripts that count the work itself: commits, sessions, tokens.",
          },
          {
            title: "Pipelines power dashboards",
            body: (
              <>
                The <Link href="/ai-pilot">pilot record</Link>, the{" "}
                <Link href="/work">work timelines</Link> and this page read what those scripts
                write.
              </>
            ),
          },
          {
            title: "Dashboards surface insights",
            body: "A number on a page gets looked at. A number in a log file does not.",
          },
          {
            title: "Insights accelerate building",
            body: "The next session starts from what the last one found, tools included.",
          },
        ]}
        returns="Each pass starts from what the last one built."
      />

      <div className="prose beta-sec">
        <p>
          Tools built for one project get used by the next. That is the part that compounds, and it
          is also the part this page cannot measure: there is no counter for a script that saved an
          afternoon six months later.
        </p>
        {frozen && (
          <p>
            The one turn of the loop I can document is a correction. The cost model behind this
            page used to regenerate every four hours, and as the session logs aged out from under
            it the numbers decayed until the file held one active day and a 1,710x velocity
            multiplier, and the page was printing &ldquo;9 months to 1 days.&rdquo; That was caught
            the plain way, by reading the page. The model is now frozen as a dated case
            study
            {typeof corrections === "number" && corrections > 0
              ? `, ${corrections} of its figures carry a written correction,`
              : ""}{" "}
            and <Link href="/cost-analysis">cost analysis</Link> says which of its own ratios it
            will not headline.
          </p>
        )}

        <h2>What it adds up to</h2>
        <p>
          The old model isn&rsquo;t broken. It&rsquo;s just no longer the only option. AI
          doesn&rsquo;t replace developers. It changes the ratio.
        </p>
        <p>
          How far the ratio moves is the part one case study cannot settle. The cost comparison
          leans on a team that was never hired
          {cover?.claudeRecordStart
            ? `, the session record it was built from only begins ${cover.claudeRecordStart}`
            : ""}
          , and two of the three ratios the pipeline computed are ones this site declines to
          headline. What is left is still worth reading: the curve and the weekly counts are on{" "}
          <Link href="/cost-analysis">cost analysis</Link>, and the whole session record is on the{" "}
          <Link href="/ai-pilot">pilot record</Link>.
        </p>
      </div>

      <div className="beta-shift-endchip">
        <BetaMeasured source="cost-model.json + ai-pilot-data.json">
          <span>
            <b>cost-model.json</b>
            {frozen
              ? `, frozen case study of ${windowLabel}, recorded ${recorded}`
              : `, generated ${recorded}`}
            {"; "}
            <b>ai-pilot-data.json</b>
            {pilotGenerated ? `, generated ${pilotGenerated}` : ", generation date not recorded"}
          </span>
        </BetaMeasured>
      </div>
    </div>
  )
}
