"use client"

import { useEffect, useState } from "react"
import { Activity } from "lucide-react"

interface PulseBucket {
  hour: string
  minutes: number
}

interface PulseData {
  generated: string
  windowHours: number
  totalActiveMinutes: number
  buckets: PulseBucket[]
}

/**
 * 24-hour Claude-session activity pulse — area chart of active minutes per
 * hour. Pulls /data/activity-pulse.json (regenerated by the build pipeline),
 * shows a glowing dot on the most recent active hour with a "Live" pill if
 * activity hit in the last two hours.
 */
export function ActivityPulse() {
  const [pulse, setPulse] = useState<PulseData | null>(null)

  useEffect(() => {
    fetch("/data/activity-pulse.json")
      .then((r) => r.json())
      .then(setPulse)
      .catch(() => {})
  }, [])

  if (!pulse || pulse.buckets.length === 0) return null

  const buckets = pulse.buckets
  const max = Math.max(...buckets.map((b) => b.minutes), 1)
  const w = 600
  const h = 64
  const padY = 4
  const barW = w / buckets.length

  const points = buckets.map((b, i) => ({
    x: i * barW + barW / 2,
    y: h - padY - (b.minutes / max) * (h - padY * 2),
  }))

  const lineD = points.reduce((acc, p, i) => {
    if (i === 0) return `M${p.x},${p.y}`
    const prev = points[i - 1]
    const cpx = (prev.x + p.x) / 2
    return `${acc} C${cpx},${prev.y} ${cpx},${p.y} ${p.x},${p.y}`
  }, "")
  const areaD = `${lineD} L${points[points.length - 1].x},${h} L${points[0].x},${h} Z`

  const lastActive = buckets.reduce((last, b, i) => (b.minutes > 0 ? i : last), -1)
  const isLive = lastActive >= buckets.length - 2

  const hourLabels = buckets
    .map((b, i) => ({
      i,
      label: new Date(b.hour + ":00Z").toLocaleTimeString([], { hour: "numeric" }),
    }))
    .filter((_, i) => i % 6 === 0)

  return (
    <article className="v3-panel">
      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          marginBottom: 14,
          gap: 12,
          flexWrap: "wrap",
        }}
      >
        <div
          style={{
            display: "inline-flex",
            alignItems: "center",
            gap: 8,
            color: "var(--v3-blue-700)",
            fontFamily: "var(--font-v3-mono), monospace",
            fontSize: 11,
            letterSpacing: "0.14em",
            textTransform: "uppercase",
            fontWeight: 700,
          }}
        >
          <Activity size={14} strokeWidth={2.25} />
          Activity pulse · last 24h
          {isLive ? (
            <span className={`v3-live v3-live--ok`} style={{ marginLeft: 8 }}>
              <span className="v3-live__dot" aria-hidden />
              live
            </span>
          ) : null}
        </div>
        <span
          style={{
            fontFamily: "var(--font-v3-mono), monospace",
            fontSize: 11,
            color: "var(--v3-slate)",
          }}
        >
          <strong style={{ color: "var(--v3-charcoal)" }}>
            {pulse.totalActiveMinutes}
          </strong>
          m active
        </span>
      </div>

      <svg
        viewBox={`0 0 ${w} ${h}`}
        style={{ width: "100%", height: 64, display: "block" }}
        preserveAspectRatio="none"
      >
        <defs>
          <linearGradient id="v3-pulse-grad" x1="0" y1="0" x2="0" y2="1">
            <stop offset="0%" stopColor="var(--v3-blue-500)" stopOpacity="0.35" />
            <stop offset="100%" stopColor="var(--v3-blue-500)" stopOpacity="0" />
          </linearGradient>
        </defs>
        <path d={areaD} fill="url(#v3-pulse-grad)" />
        <path
          d={lineD}
          fill="none"
          stroke="var(--v3-blue-600)"
          strokeWidth="2"
          strokeLinecap="round"
        />
        {points.map((p, i) =>
          buckets[i].minutes > 0 ? (
            <circle
              key={i}
              cx={p.x}
              cy={p.y}
              r="2.6"
              fill="var(--v3-blue-600)"
              opacity="0.85"
            />
          ) : null
        )}
        {lastActive >= 0 ? (
          <circle
            cx={points[lastActive].x}
            cy={points[lastActive].y}
            r="5"
            fill="var(--v3-blue-500)"
            opacity="0.45"
          >
            <animate attributeName="r" values="4;9;4" dur="2.2s" repeatCount="indefinite" />
            <animate
              attributeName="opacity"
              values="0.5;0.05;0.5"
              dur="2.2s"
              repeatCount="indefinite"
            />
          </circle>
        ) : null}
      </svg>

      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          marginTop: 6,
          padding: "0 4px",
          fontFamily: "var(--font-v3-mono), monospace",
          fontSize: 10,
          color: "var(--v3-slate)",
        }}
      >
        {hourLabels.map((hl) => (
          <span key={hl.i}>{hl.label}</span>
        ))}
        <span>Now</span>
      </div>
    </article>
  )
}
