#!/usr/bin/env python3
"""
repo-code-stats.py — line-count / code inventory across a set of GitHub repos.

Built for the Campaign Brain consolidation effort: shallow-clone every matching
repo, count lines by language (SLOC-approximate — non-blank lines, no comment
stripping), and emit a per-repo + per-language + grand-total report. This is the
inventory step toward normalizing cb* into one library.

  python3 scripts/repo-code-stats.py                      # default targets below
  python3 scripts/repo-code-stats.py --update             # git pull existing clones
  python3 scripts/repo-code-stats.py --targets Nominate-AI:cb* Sysforge-AI:*
  python3 scripts/repo-code-stats.py --json data/cb-code-stats.json

Requires: gh (authenticated), git.
"""

import argparse
import concurrent.futures as cf
import fnmatch
import json
import os
import subprocess
import sys
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

DEFAULT_TARGETS = ["Nominate-AI:cb*", "Sysforge-AI:*"]
DEFAULT_CACHE = Path.home() / ".cache" / "cb-code"
DEFAULT_JSON = Path(__file__).resolve().parent.parent / "data" / "cb-code-stats.json"

# Directories never counted (vcs / deps / build / generated / vendored).
SKIP_DIRS = {
    ".git", "node_modules", ".venv", "venv", "env", "__pycache__", ".mypy_cache",
    ".pytest_cache", ".ruff_cache", "dist", "build", ".next", ".nuxt", "out",
    "vendor", "target", ".cache", "site-packages", "bower_components", "coverage",
    ".terraform", ".idea", ".vscode", ".gradle", "__snapshots__", ".turbo",
    "migrations",  # autogenerated schema churn — usually not "authored" code
}
EXT_LANG = {
    ".py": "Python", ".pyi": "Python",
    ".ts": "TypeScript", ".tsx": "TypeScript",
    ".js": "JavaScript", ".jsx": "JavaScript", ".mjs": "JavaScript", ".cjs": "JavaScript",
    ".go": "Go", ".rs": "Rust", ".rb": "Ruby", ".java": "Java", ".kt": "Kotlin",
    ".c": "C", ".h": "C", ".cpp": "C++", ".cc": "C++", ".hpp": "C++",
    ".sh": "Shell", ".bash": "Shell", ".zsh": "Shell",
    ".sql": "SQL", ".html": "HTML", ".htm": "HTML", ".css": "CSS", ".scss": "CSS",
    ".vue": "Vue", ".svelte": "Svelte", ".php": "PHP", ".lua": "Lua",
    ".md": "Markdown", ".mdx": "MDX", ".rst": "reStructuredText",
    ".yaml": "YAML", ".yml": "YAML", ".toml": "TOML", ".json": "JSON",
    ".tf": "Terraform", ".dockerfile": "Dockerfile", ".proto": "Protobuf",
}
SPECIAL_NAMES = {"Dockerfile": "Dockerfile", "Makefile": "Makefile"}
MAX_BYTES = 2_000_000  # skip files bigger than this (data / minified / generated)


def sh(args, cwd=None, timeout=300):
    return subprocess.run(args, cwd=cwd, capture_output=True, text=True, timeout=timeout)


def list_repos(org: str, patterns: list[str]) -> list[str]:
    r = sh(["gh", "repo", "list", org, "--limit", "500", "--json", "name"])
    if r.returncode != 0:
        print(f"  ! gh repo list {org} failed: {r.stderr.strip()[:120]}", flush=True)
        return []
    names = [x["name"] for x in json.loads(r.stdout or "[]")]
    keep = [n for n in names if any(fnmatch.fnmatch(n.lower(), p.lower()) for p in patterns)]
    return sorted(keep)


def clone_or_update(org: str, name: str, cache: Path, update: bool) -> Path | None:
    dest = cache / org / name
    if dest.exists():
        if update:
            sh(["git", "-C", str(dest), "fetch", "--depth", "1", "origin"], timeout=180)
            sh(["git", "-C", str(dest), "reset", "--hard", "@{u}"], timeout=60)
        return dest
    dest.parent.mkdir(parents=True, exist_ok=True)
    # gh repo clone uses the authenticated gh token (repos are private).
    r = sh(["gh", "repo", "clone", f"{org}/{name}", str(dest), "--", "--depth", "1"], timeout=600)
    if r.returncode != 0:
        print(f"  ! clone {org}/{name} failed: {r.stderr.strip()[:120]}", flush=True)
        return None
    return dest


def is_binary(path: Path) -> bool:
    try:
        with open(path, "rb") as f:
            return b"\x00" in f.read(4096)
    except OSError:
        return True


def lang_of(path: Path) -> str | None:
    if path.name in SPECIAL_NAMES:
        return SPECIAL_NAMES[path.name]
    return EXT_LANG.get(path.suffix.lower())


def count_repo(root: Path) -> dict:
    by_lang = defaultdict(lambda: {"files": 0, "lines": 0, "code": 0})
    tot = {"files": 0, "lines": 0, "code": 0, "bytes": 0}
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS and not d.startswith(".git")]
        for fn in filenames:
            p = Path(dirpath) / fn
            lang = lang_of(p)
            if lang is None:
                continue
            try:
                sz = p.stat().st_size
            except OSError:
                continue
            if sz == 0 or sz > MAX_BYTES or is_binary(p):
                continue
            lines = code = 0
            try:
                with open(p, "r", errors="replace") as f:
                    for line in f:
                        lines += 1
                        if line.strip():
                            code += 1
            except OSError:
                continue
            by_lang[lang]["files"] += 1
            by_lang[lang]["lines"] += lines
            by_lang[lang]["code"] += code
            tot["files"] += 1
            tot["lines"] += lines
            tot["code"] += code
            tot["bytes"] += sz
    return {"total": tot, "by_language": dict(by_lang)}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--targets", nargs="+", default=DEFAULT_TARGETS,
                    help="ORG:glob entries, e.g. Nominate-AI:cb* Sysforge-AI:*")
    ap.add_argument("--cache", default=str(DEFAULT_CACHE))
    ap.add_argument("--json", default=str(DEFAULT_JSON))
    ap.add_argument("--jobs", type=int, default=8)
    ap.add_argument("--update", action="store_true", help="git pull existing clones")
    args = ap.parse_args()
    cache = Path(args.cache)

    # 1. resolve target repos
    repos: list[tuple[str, str]] = []
    for t in args.targets:
        org, _, glob = t.partition(":")
        pats = [g.strip() for g in (glob or "*").split(",")]
        found = list_repos(org, pats)
        print(f"  {org}: {len(found)} repos match {pats}", flush=True)
        repos += [(org, n) for n in found]
    print(f"total target repos: {len(repos)}", flush=True)

    # 2. clone/update in parallel
    dests: dict[tuple[str, str], Path] = {}
    done = 0
    with cf.ThreadPoolExecutor(max_workers=args.jobs) as ex:
        futs = {ex.submit(clone_or_update, o, n, cache, args.update): (o, n) for o, n in repos}
        for fut in cf.as_completed(futs):
            on = futs[fut]
            d = fut.result()
            if d:
                dests[on] = d
            done += 1
            if done % 10 == 0:
                print(f"  cloned/updated {done}/{len(repos)}", flush=True)
    print(f"cloned {len(dests)}/{len(repos)}", flush=True)

    # 3. count (parallel)
    per_repo = {}
    with cf.ThreadPoolExecutor(max_workers=args.jobs) as ex:
        futs = {ex.submit(count_repo, d): on for on, d in dests.items()}
        for fut in cf.as_completed(futs):
            org, name = futs[fut]
            per_repo[f"{org}/{name}"] = fut.result()

    # 4. aggregate
    lang_tot = defaultdict(lambda: {"files": 0, "lines": 0, "code": 0})
    grand = {"repos": len(per_repo), "files": 0, "lines": 0, "code": 0, "bytes": 0}
    for stats in per_repo.values():
        for lang, v in stats["by_language"].items():
            for k in ("files", "lines", "code"):
                lang_tot[lang][k] += v[k]
        for k in ("files", "lines", "code", "bytes"):
            grand[k] += stats["total"][k]

    out = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "targets": args.targets,
        "grand_total": grand,
        "by_language": dict(sorted(lang_tot.items(), key=lambda kv: -kv[1]["code"])),
        "repos": dict(sorted(per_repo.items(), key=lambda kv: -kv[1]["total"]["code"])),
    }
    outp = Path(args.json)
    outp.parent.mkdir(parents=True, exist_ok=True)
    outp.write_text(json.dumps(out, indent=2))

    # 5. summary
    print("\n=== code inventory ===")
    print(f"  repos {grand['repos']} · files {grand['files']:,} · "
          f"lines {grand['lines']:,} · code(SLOC~) {grand['code']:,} · "
          f"{grand['bytes']/1e6:.0f} MB")
    print("\n  by language (code lines):")
    for lang, v in list(out["by_language"].items())[:14]:
        print(f"    {lang:16} {v['code']:>10,}  ({v['files']:,} files)")
    print("\n  top 15 repos (code lines):")
    for name, s in list(out["repos"].items())[:15]:
        print(f"    {name:34} {s['total']['code']:>9,}")
    print(f"\n  → {outp}")


if __name__ == "__main__":
    sys.exit(main())
