import { readFile } from "node:fs/promises"
import { join } from "node:path"

// Serves the private Claude-activity aggregates (data/pilot-analytics.json,
// generated by scripts/claude-activity-viz.py). Not in public/ so the raw file
// isn't statically served or mirrored. 503 if the aggregate hasn't been built.
export const dynamic = "force-dynamic"

export async function GET() {
  try {
    const p = join(process.cwd(), "data", "pilot-analytics.json")
    const body = await readFile(p, "utf8")
    return new Response(body, {
      status: 200,
      headers: { "content-type": "application/json", "cache-control": "no-store" },
    })
  } catch {
    return Response.json(
      { error: "not_built", message: "run scripts/claude-activity-viz.py" },
      { status: 503 }
    )
  }
}
